### ISSUE TITLE
[Bug]: Buffer is not defined in @quirks/wallets v0.20.0

### ISSUE THREAD

**Issue by arlai-mk** [nabla-studio/quirks#105]
### Prerequisites

- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Quirks.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

I have a web app using Vue, Vite, and Quirks.

In my package.json, I have the below:
```json
    "@quirks/core": "^0.19.0",
    "@quirks/store": "^0.27.0",
    "@quirks/vue": "^0.12.5",
    "@quirks/wallets": "^0.19.0",
```
And it all works fine.

When I change to latest version of @quirks/wallets:
```diff
    "@quirks/core": "^0.19.0",
    "@quirks/store": "^0.27.0",
    "@quirks/vue": "^0.12.5",
+   "@quirks/wallets": "^0.20.0",
-   "@quirks/wallets": "^0.19.0",
```

### Describe the issue behavior

Then, if I run `npm install`, and `npm run dev`, I can still access my web app as usual.
However, after building it (`npm run build`) and deploying in production, loading the web app will result in a blank page, and the below error showing in console:
```
Uncaught ReferenceError: Buffer is not defined
    at index-BHeQET0V.js:329:129287
```
The error points to the below code:
```js
var bnExports = bn.exports;
const createHmac = browser$1
  , ONE1 = Buffer.alloc(1, 1)
  , ZERO1 = Buffer.alloc(1, 0);
function deterministicGenerateK$1(g, A, v, _, b) {
    let B = Buffer.alloc(32, 0)
```

**Comment by DavideSegullo** [comment]
Hello @arlai-mk , thank you for reporting this issue. I'll check it in a few hours and I'll get back to you with a response, I think it's due to vite setup, in the meantime can you try this to add polyfills inside your `vite.config.js`?

```js
import { defineConfig } from 'vite'
import { nodePolyfills } from 'vite-plugin-node-polyfills'

export default defineConfig({
  plugins: [nodePolyfills()]
})
```

**Comment by arlai-mk** [comment]
Hi @DavideSegullo,

Thanks for the prompt answer. 
I just tested it and confirm that it is working with the polyfills inside my `vite.config.js`.

You can close this bug, but maybe it can be worth it mentioning somewhere in the documentation for others who may be facing the same issue :)

Thank you again.

arlai

**Comment by DavideSegullo** [comment]
Ye thank you, I'll try to find a fix no one will need to polyfill it, for now I'll leave this issue open. Otherwise I'll add some details inside the doc, thank you!!

**Comment by DavideSegullo** [comment]
@arlai-mk Fixed, now you don't need to add polyfills

**Comment by DavideSegullo** [comment]
No problem! If you have other issues, feel free to ping me!
